services:
  - type: web
    name: golf-mgmt-api
    env: python
    buildCommand: |
      echo "開始安裝依賴..."
      pip install -r requirements.txt
      echo "建置完成"
      
      echo "開始資料庫初始化..."
      export FLASK_APP=run.py
      export PYTHONPATH=$PWD
      python -c "
      from flask_migrate import upgrade
      print('執行資料庫遷移...')
      upgrade()
      print('資料庫遷移完成')
      
      from app import db
      print('檢查資料庫連接...')
      db.engine.connect()
      print('資料庫連接成功')
      
      print('執行初始化腳本...')
      "
      python init_db.py
      echo "資料庫初始化完成"
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        sync: false
      - key: FLASK_DEBUG
        value: 0

databases:
  - name: golf-mgmt-db
    databaseName: golf_mgmt
    user: golf_mgmt
    region: singapore  # 指定區域
    ipAllowList: []  # 允許所有 IP 訪問
    plan: free 