services:
  - type: web
    name: golf-mgmt-api
    env: python
    buildCommand: |
      echo "開始安裝依賴..."
      pip install -r requirements.txt
      echo "環境變數 DATABASE_URL: $DATABASE_URL"
      echo "開始執行資料庫遷移..."
      flask db upgrade
      echo "資料庫遷移完成"
      echo "開始初始化資料庫..."
      python init_db.py
      echo "建置完成"
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: golf-mgmt-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: FLASK_DEBUG
        value: 0

databases:
  - name: golf-mgmt-db
    databaseName: golf_mgmt
    user: golf_mgmt
    region: singapore  # 指定區域
    ipAllowList: []  # 允許所有 IP 訪問
    plan: free 