services:
  - type: web
    name: golf-mgmt-api
    env: python
    buildCommand: |
      echo "開始安裝依賴..."
      pip install -r requirements.txt
      echo "建置完成"
      
      echo "開始資料庫初始化..."
      echo "當前目錄: $PWD"
      echo "列出目錄內容:"
      ls -la
      
      echo "設置環境變數..."
      export FLASK_APP=run.py
      export PYTHONPATH=$PWD
      
      echo "執行初始化腳本..."
      PYTHONUNBUFFERED=1 python init_render.py
      
      echo "資料庫初始化流程完成"
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        sync: false
      - key: FLASK_DEBUG
        value: 0

databases:
  - name: golf-mgmt-db
    databaseName: golf_mgmt
    user: golf_mgmt
    region: singapore  # 指定區域
    ipAllowList: []  # 允許所有 IP 訪問
    plan: free 