services:
  - type: web
    name: golf-mgmt-api
    env: python
    buildCommand: |
      echo "開始安裝依賴..."
      pip install -r requirements.txt
      echo "建置完成"
    startCommand: |
      echo "設置環境變數..."
      export FLASK_APP=run.py
      export PYTHONPATH=$PWD
      
      echo "執行資料庫遷移..."
      python db_setup.py || exit 1
      
      echo "啟動應用程式..."
      PYTHONUNBUFFERED=1 gunicorn run:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: 0
      - key: DATABASE_URL
        fromDatabase:
          name: golf-mgmt-db
          property: connectionString

databases:
  - name: golf-mgmt-db
    databaseName: golf_mgmt
    user: golf_mgmt
    region: singapore
    ipAllowList: []
    plan: free