services:
  - type: web
    name: golf-mgmt-1-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    headers:
      - path: /*
        name: Cache-Control
        value: no-store, no-cache, must-revalidate
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-XSS-Protection
        value: 1; mode=block
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://golf-mgmt-1-frontend.onrender.com
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, DELETE, OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Origin, X-Requested-With, Content-Type, Accept, Authorization
      - path: /*
        name: Access-Control-Allow-Credentials
        value: "true"
    routes:
      - type: rewrite
        source: /api/*
        destination: https://golf-mgmt-1.onrender.com/api/:splat
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_API_URL
        value: https://golf-mgmt-1.onrender.com 