services:
  - type: web
    name: golf-mgmt-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      flask db upgrade
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        value: sqlite:///app.db
      - key: SECRET_KEY
        sync: false
      - key: FLASK_DEBUG
        value: 0 