"""add gender field to member model

Revision ID: 02c807f51d4a
Revises: 46cd9ed55557
Create Date: 2025-01-10 22:04:42.023796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c807f51d4a'
down_revision = '46cd9ed55557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('gender', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'gender')
    # ### end Alembic commands ###
