"""update yearly champions table fields

Revision ID: 06ec44a9b862
Revises: 02c807f51d4a
Create Date: 2025-01-10 22:14:24.418862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ec44a9b862'
down_revision = '02c807f51d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yearly_champions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=100), nullable=False),
    sa.Column('member_name', sa.String(length=100), nullable=False),
    sa.Column('member_number', sa.String(length=20), nullable=False),
    sa.Column('total_strokes', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('yearly_champion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yearly_champion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tournament_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('player_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('total_strokes', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('yearly_champions')
    # ### end Alembic commands ###
