"""新增獎項管理功能的資料表

Revision ID: 07175fb5defc
Revises: 831cfc140ae4
Create Date: 2025-02-12 16:27:34.038682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07175fb5defc'
down_revision = '831cfc140ae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('has_category', sa.Boolean(), nullable=True),
    sa.Column('has_score', sa.Boolean(), nullable=True),
    sa.Column('has_rank', sa.Boolean(), nullable=True),
    sa.Column('has_hole_number', sa.Boolean(), nullable=True),
    sa.Column('max_winners', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tournament_awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('award_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('winner_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('hole_number', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_awards')
    op.drop_table('award_types')
    # ### end Alembic commands ###
