"""remove member_number from yearly champions

Revision ID: 47a57b9a8364
Revises: 06ec44a9b862
Create Date: 2025-01-10 22:17:47.031337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a57b9a8364'
down_revision = '06ec44a9b862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yearly_champions', 'member_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yearly_champions', sa.Column('member_number', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
