"""add game prizes and game type

Revision ID: 56824c268f61
Revises: 18eee20e3cdb
Create Date: 2025-01-12 00:53:47.872865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56824c268f61'
down_revision = '18eee20e3cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_prizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('games', sa.Column('config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'config')
    op.drop_column('games', 'type')
    op.drop_table('game_prizes')
    # ### end Alembic commands ###
