"""add versions table

Revision ID: 5d67cc6ad79c
Revises: 05f75860affe
Create Date: 2025-01-13 12:18:03.636252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d67cc6ad79c'
down_revision = '05f75860affe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('versions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('versions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('versions', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('versions', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
