"""Add rank column to Score model

Revision ID: a04aeb69ee6e
Revises: 5a56942914d5
Create Date: 2025-01-10 15:43:53.621398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a04aeb69ee6e'
down_revision = '5a56942914d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('score', sa.Column('handicap', sa.Float(), nullable=True))
    op.add_column('score', sa.Column('new_handicap', sa.Float(), nullable=True))
    op.add_column('score', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'updated_at')
    op.drop_column('score', 'new_handicap')
    op.drop_column('score', 'handicap')
    op.drop_column('score', 'rank')
    # ### end Alembic commands ###
