"""add net_score field to score model

Revision ID: ccdddec8f21d
Revises: eda88294cf63
Create Date: 2025-01-10 22:57:18.146999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccdddec8f21d'
down_revision = 'eda88294cf63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('score', sa.Column('net_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('score', 'net_score')
    # ### end Alembic commands ###
