"""Add yearly champions table

Revision ID: fafdef862d27
Revises: update_score_fields
Create Date: 2025-01-10 17:12:56.438041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fafdef862d27'
down_revision = 'update_score_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yearly_champion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_name', sa.String(length=128), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=False),
    sa.Column('total_strokes', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yearly_champion')
    # ### end Alembic commands ###
